name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - run: go build -o bin/${{ matrix.arch }}/ ./cmd/containerd ./cmd/ctr
        env:
          GOOS: darwin
          GOARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: bin/*
